name: Build Windows EXE and Zip on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build Windows EXE with PyInstaller (no console)
        run: |
          python -m PyInstaller --name VRCitizenLauncher-Debug --onefile --noconsole main.py

      - name: Prepare folder structure for ZIP
        run: |
          New-Item -ItemType Directory -Path build_output\VRCitizenLauncher-Debug | Out-Null
          Copy-Item -Path dist\VRCitizenLauncher-Debug.exe -Destination build_output\VRCitizenLauncher-Debug\
          Copy-Item -Path image.png -Destination build_output\VRCitizenLauncher-Debug\
          Copy-Item -Path templates.json -Destination build_output\VRCitizenLauncher-Debug\
          Copy-Item -Recurse -Path locales -Destination build_output\VRCitizenLauncher-Debug\
        shell: pwsh

      - name: Create zip archive
        run: |
          Compress-Archive -Path VRCitizenLauncher-Debug -DestinationPath ../VRCitizenLauncher-Debug.zip
        shell: pwsh
        working-directory: build_output

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: VRCitizenLauncher-Debug
          path: VRCitizenLauncher-Debug.zip
          retention-days: 7

      - name: Comment on PR with download link
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ✅ Windows build complete! You can download the ZIP file from the [Actions tab](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
