name: Build and Zip on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          python -m PyInstaller --name VRCitizenLauncher-Debug --onefile main.py

      - name: Prepare zip content
        run: |
          mkdir build_output
          cp dist/VRCitizenLauncher-Debug build_output/
          cp image.png build_output/
          cp -r locales build_output/

      - name: Create zip archive
        run: |
          cd build_output
          zip -r ../VRCitizenLauncher-Debug.zip .

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: VRCitizenLauncher-Debug
          path: VRCitizenLauncher-Debug.zip

      - name: Comment with artifact link
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: artifact-comment.md

  post-comment:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: VRCitizenLauncher-Debug
          path: artifact

      - name: Create comment content
        run: |
          echo "✅ Build complete! Download the [zip artifact](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" > artifact-comment.md
